// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "skychat-lib.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNSkychatLibSpec.h"

@interface SkychatLib : NSObject <NativeSkychatLibSpec>
#else
#import <React/RCTBridgeModule.h>

@interface SkychatLib : NSObject <RCTBridgeModule>
#endif

@end